export const FETCH_WIDGET_CONFIG   = 'FETCH_WIDGET_CONFIG';
export const WIDGET_CONFIG_SUCCESS = 'WIDGET_CONFIG_SUCCESS';
export const WIDGET_CONFIG_FAILURE = 'WIDGET_CONFIG_FAILURE';
export const DATA_CONFIG_SUCCESS   = 'DATA_CONFIG_SUCCESS';
export const DATA_CONFIG_FAILURE   = 'DATA_CONFIG_FAILURE';
export const FETCH_DATA_REQUEST    = 'FETCH_DATA_REQUEST';
