export const UPDATE_NAVIGATION_BAR_TITLE = 'UPDATE_NAVIGATION_BAR_TITLE';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_APP_CONFIG = 'SET_APP_CONFIG';
export const SET_APP_CONFIG_ERROR = 'SET_APP_CONFIG_ERROR';
export const IS_NAVIGATION_BAR_TITLE_ENABLED = 'IS_NAVIGATION_BAR_TITLE_ENABLED';

